// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
//Contests
export const FETCH_CONTESTS = 'FETCH_CONTESTS'
export const FETCH_CONTEST = 'FETCH_CONTEST'
export const FETCH_CONTEST_RESULTS = 'FETCH_CONTEST_RESULTS'
// Contestants
export const FETCH_CONTESTANT = 'FETCH_CONTESTANT'
export const FETCH_CONTESTANTS = 'FETCH_CONTESTANTS'
//Tasks
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASK = 'FETCH_TASK'
// Regions
export const FETCH_REGIONS = 'FETCH_REGIONS'
export const FETCH_REGION = 'FETCH_REGION'
export const FETCH_REGION_RESULTS = 'FETCH_REGION_RESULTS'
