#%RAML 1.0
title: oii-stats
version: v1
baseUri: https://stats.olinfo.it/api
types: !include types.raml

/contests:
  get:
    description: Get the list of the contests with basic information
    responses:
      200:
        body:
          application/json:
            type: contests
            example: !include examples/contests.json

  /{year}:
    uriParameters:
      year: integer
    get:
      description: Get the contest information for a single year
      responses:
        200:
          body:
            application/json:
              type: contest
              example: !include examples/contest.json
        404:
          body:
            application/json:
              type: error

    /results:
      get:
        description: Get the list of participants with all the raw information
        responses:
          200:
            body:
              application/json:
                type: contest_results
                example: !include examples/contest_results.json

    /regions:
      get:
        description: Get the list of regions and the grouped information
        responses:
          200:
            body:
              application/json:
                type: contest_regions
                example: !include examples/contest_regions.json

    /tasks:
      get:
        description: Get the list of the tasks and grouped information
        responses:
          200:
            body:
              application/json:
                type: contest_tasks
                example: !include examples/contest_tasks.json

/regions:
  get:
    description: Get the list of the regions with some basic information
    responses:
      200:
        body:
          application/json:
            type: regions
            example: !include examples/regions.json

  /{region}:
    uriParameters:
      region: string
    get:
      description: Get the details of a single region
      responses:
        200:
          body:
            application/json:
              type: detailed_region
              example: !include examples/detailed_region.json

    /results:
      get:
        description: Get the list of participants of a particular region
        responses:
          200:
            body:
              application/json:
                type: region_results
                example: !include examples/region_results.json

/tasks:
  get:
    description: Get the list of the tasks with some basic information
    responses:
      200:
        body:
          application/json:
            type: tasks
            example: !include examples/tasks.json
  /{year}/{task}:
    uriParameters:
      year: integer
      task: string
    get:
      description: Get the detailed information about a task
      responses:
        200:
          body:
            application/json:
              type: task_detail
              example: !include examples/task_detail.json
