#%RAML 1.0
title: oii-stats
version: v1
baseUri: https://stats.olinfo.it/api
types: !include types.raml

/contests:
  get:
    description: Get the list of the contests with basic information
    responses:
      200:
        body:
          application/json:
            type: contests
            example: !include examples/contests.json

  /{year}:
    uriParameters:
      year: integer
    get:
      description: Get the contest information for a single year
      responses:
        200:
          body:
            application/json:
              type: contest_detail
              example: !include examples/contest.json
        404:
          body:
            application/json:
              type: error

    /results:
      get:
        description: Get the list of participants with all the raw information
        responses:
          200:
            body:
              application/json:
                type: contest_results
                example: !include examples/contest_results.json
          404:
            body:
              application/json:
                type: error

    /regions:
      get:
        description: Get the list of regions and the grouped information
        responses:
          200:
            body:
              application/json:
                type: contest_regions
                example: !include examples/contest_regions.json
          404:
            body:
              application/json:
                type: error

    /tasks:
      get:
        description: Get the list of the tasks and grouped information
        responses:
          200:
            body:
              application/json:
                type: contest_tasks
                example: !include examples/contest_tasks.json
          404:
            body:
              application/json:
                type: error

/regions:
  get:
    description: Get the list of the regions with some basic information
    responses:
      200:
        body:
          application/json:
            type: regions
            example: !include examples/regions.json

  /{region}:
    uriParameters:
      region: string
    get:
      description: Get the details of a single region
      responses:
        200:
          body:
            application/json:
              type: detailed_region
              example: !include examples/detailed_region.json
        404:
          body:
            application/json:
              type: error

    /results:
      get:
        description: Get the list of participants of a particular region
        responses:
          200:
            body:
              application/json:
                type: region_results
                example: !include examples/region_results.json
          404:
            body:
              application/json:
                type: error

/tasks:
  get:
    description: Get the list of the tasks with some basic information
    responses:
      200:
        body:
          application/json:
            type: tasks
            example: !include examples/tasks.json
      404:
        body:
          application/json:
            type: error

  /{year}/{task}:
    uriParameters:
      year: integer
      task: string
    get:
      description: Get the detailed information about a task
      responses:
        200:
          body:
            application/json:
              type: task_detail
              example: !include examples/task_detail.json
        404:
          body:
            application/json:
              type: error

/users:
  get:
    description: Get the list of the users
    responses:
      200:
        body:
          application/json:
            type: users
            example: !include examples/users.json

  /{user_id}:
    get:
      description: Get the details of a user
      responses:
        200:
          body:
            application/json:
              type: user_detail
              example: !include examples/user_detail.json
        404:
          body:
            application/json:
              type: error

/search:
  get:
    queryParameters:
      q: string
    description: Search for users, tasks or contests
    responses:
      200:
        body:
          application/json:
            type: search_results
            example: !include examples/search_results.json
