error:
  type: object
  properties:
    error: string

num_medals:
  type: object
  properties:
    gold: integer?
    silver: integer?
    bronze: integer?

contestant:
  type: object
  properties:
    id: string
    first_name: string
    last_name: string

medal:
  type: string?
  enum: [gold, silver, bronze, ~]

contest_info_task:
  type: object
  properties:
    name: string
    title: string
    link: string?
    index: integer
    max_score_possible: number?

location:
  type: object
  properties:
    location: string?
    gmaps: string?
    latitude: number?
    longitude: number?

contest:
  type: object
  properties:
    year: integer
    location: location
    region: string?
    num_contestants: integer?
    max_score_possible: number?
    max_score: number?
    avg_score: number?
    tasks:
      type: array
      items: contest_info_task
    medals:
      type: object
      properties:
        gold:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal
        silver:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal
        bronze:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal

contest_detail:
  type: object
  properties:
    navigation:
      type: object
      properties:
        current: integer
        previous: integer?
        next: integer?
    location: location
    region: string?
    num_contestants: integer?
    max_score_possible: number?
    max_score: number?
    avg_score: number?
    tasks:
      type: array
      items: contest_task
    medals:
      type: object
      properties:
        gold:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal
        silver:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal
        bronze:
          type: object
          properties:
            number: integer?
            cutoff:
              type: number?
              description: Minimum score to get this medal

contests:
  type: object
  properties:
    contests:
      type: array
      items: contest

contest_result:
  type: object
  properties:
    rank: integer?
    contestant: contestant
    region: string?
    score: number?
    scores:
      type: array
      items: number?
    medal: medal
    past_participations:
      type: array
      items:
        type: object
        properties:
          year: integer
          medal: medal

contest_results:
  type: object
  properties:
    navigation:
      type: object
      properties:
        current: integer
        previous: integer?
        next: integer?
    tasks:
      type: array
      items: string
    results:
      type: array
      items: contest_result

contest_region:
  type: object
  properties:
    name: string
    num_participants: integer?
    num_medals: num_medals
    max_score: number?
    avg_score: number?

contest_regions:
  type: object
  properties:
    navigation:
      type: object
      properties:
        current: integer
        previous: integer?
        next: integer?
    regions:
      type: array
      items: contest_region

contest_task:
  type: object
  properties:
    name: string
    title: string
    link: string?
    index: integer
    max_score_possible: number?
    max_score: number?
    avg_score: number?
    # TODO add num_full_scores

contest_tasks:
  type: object
  properties:
    navigation:
      type: object
      properties:
        current: integer
        previous: integer?
        next: integer?
    tasks:
      type: array
      items: contest_task

region:
  type: object
  properties:
    id: string
    name: string
    num_contestants: integer?
    medals: num_medals
    avg_contestants_per_year: number?
    hosted:
      type: array
      items: integer

regions:
  type: object
  properties:
    regions:
      type: array
      items: region

detailed_region:
  type: object
  properties:
    name: string
    navigation:
      type: object
      properties:
        current: string
        previous: string?
        next: string?
    years:
      type: array
      items:
        type: object
        properties:
          year: integer
          location: location
          num_contestants: integer
          num_medals: num_medals
    hosted:
      type: array
      items: integer

region_contestant_result:
  type: object
  properties:
    contestant: contestant
    rank: integer?
    medal: medal
    task_scores:
      type: array
      items:
        type: object
        properties:
          name: string
          score: number?
          max_score_possible: number?

region_result:
  type: object
  properties:
    year: integer
    contestants:
      type: array
      items: region_contestant_result

region_results:
  type: object
  properties:
    navigation:
      type: object
      properties:
        current: string
        previous: string?
        next: string?
    results:
      type: array
      items: region_result

task:
  type: object
  properties:
    name: string
    title: string
    link: string?
    index: integer
    max_score_possible: number?
    max_score: number?
    avg_score: number?

tasks:
  type: object
  properties:
    tasks:
      type: array
      items:
        type: object
        properties:
          year: integer
          tasks:
            type: array
            items: task

task_detail:
  type: object
  properties:
    title: string
    link: string?
    index: integer
    navigation:
      type: object
      properties:
        current:
          type: object
          required: false
          properties:
            year: integer
            name: string
        previous:
          type: object
          required: false
          properties:
            year: integer
            name: string
        next:
          type: object
          required: false
          properties:
            year: integer
            name: string
    max_score_possible: number?
    scores:
      type: array
      items:
        type: object
        properties:
          contestant: contestant
          rank: integer?
          score: number?

user:
  type: object
  properties:
    contestant: contestant
    num_medals: num_medals
    best_rank: integer?
    participations:
      type: array
      items:
        type: object
        properties:
          year: integer
          medal: medal

users:
  type: object
  properties:
    users:
      type: array
      items: user

user_detail:
  type: object
  properties:
    contestant: contestant
    participations:
      type: array
      items:
        type: object
        properties:
          year: integer
          medal: medal
          rank: integer?
          scores:
            type: array
            items:
              type: object
              properties:
                task: string
                score: number?
                max_score_possible: number?

search_result_user:
  type: object
  properties:
    user:
      type: user

search_result_task:
  type: object
  properties:
    task:
      type: object
      properties:
        year: number
        task: task

search_result_contest:
  type: object
  properties:
    contest: contest

search_result_region:
  type: object
  properties:
    region:
      type: region

search_result:
  type: search_result_user | search_result_task | search_result_contest | search_result_region

search_results:
  type: object
  properties:
    results:
      type: array
      items: search_result
